apiVersion: v1
kind: Service
metadata:
  name: nats
  labels:
    app.kubernetes.io/name: nats
    app.kubernetes.io/part-of: software-factory
spec:
  selector:
    app.kubernetes.io/name: nats
  ports:
    - port: 4222
      targetPort: client
      name: client
      protocol: TCP
    - port: 8222
      targetPort: monitor
      name: monitor
      protocol: TCP
