apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - bases/factory.example.com_agentconfigs.yaml
  - bases/factory.example.com_pools.yaml
  - bases/factory.example.com_sandboxes.yaml
  - bases/factory.example.com_sessions.yaml
  - bases/factory.example.com_tasks.yaml
  - bases/factory.example.com_workflows.yaml
